# Site settings
author: Nicolas Marini
title: Tech-Talk
header-img: img/home-bg.png
email: nmarini44@gmail.com
copyright_name: Nicolas Marini
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on programming and technology in general. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nmarini

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
